spring:
  application:
    name: bashdata

  profiles:
    active: dev

  jackson:
    serialization:
      INDENT_OUTPUT: true

application:
  security:
    jwt:
      issuer: BashData
      secret-key: BashDataDevelopmentSecretKey2026SuperSecure123456
      access-token-expiration: 1h
      refresh-token-expiration: 7d

server:
  port: 8080